### PR TITLE
chore: change company name

### PR DESCRIPTION
**Pull request by jung-han**
#24

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by jung-han** [comment]
ok to test

**Comment by jung-han** [comment]
ok to test

**Comment by jung-han** [comment]
ok to test

**Comment by jung-han** [comment]
ok to test

**Comment by jung-han** [comment]
ok to test

**Comment by jung-han** [comment]
ok to test

**Pull request closed without merging**
